name: Tackle Pathfinder CI PR Minikube Test

on:
  pull_request:
    branches: [ main ]

jobs:
  microcks-api-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
          driver: docker
          start args: '--addons=registry --addons=ingress'
#      - name: Build Pathfinder image and push it to the minikube docker host
#        run: |
#          cd ${{github.workspace}}
#          ./mvnw -U -B package -DskipTests -Pnative \
#            -Dquarkus.container-image.push=false \
#           -Dquarkus.container-image.build=true \
#            -Dquarkus.container-image.group=${{ github.repository_owner }} \
#            -Dquarkus.container-image.additional-tags=latest-jar \
#            -Dquarkus.container-image.tag=0.0.1-SNAPSHOT-native \
#            -Dquarkus.container-image.registry=quay.io \
#            -Dquarkus.native.container-build=true
#          minikube cache add quay.io/konveyor/tackle-pathfinder:0.0.1-SNAPSHOT-native
      - name: Sleep for 60 seconds to allow Minikube to be ready
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: Install Helm
        run: |
          wget https://get.helm.sh/helm-v3.5.3-linux-amd64.tar.gz
          tar -zxvf helm-v3.5.3-linux-amd64.tar.gz
      - name: Install Microcks on minikube
        run: |
          ./linux-amd64/helm repo add microcks https://microcks.io/helm
          kubectl create namespace microcks
          ./linux-amd64/helm install microcks microcks/microcks --version 1.2.0 \
            --namespace microcks --set microcks.url=microcks.$(minikube ip).nip.io \
            --set keycloak.url=keycloak.$(minikube ip).nip.io
      - name: Deploy Pathfinder on minikube
        run: |
          kubectl create namespace tackle
          kubectl apply -f src/test/resources/test-deployment.yaml -n tackle
          kubectl apply -f src/main/kubernetes/tackle-pathfinder.yaml -n tackle
      - name: Sleep for 360 seconds to allow objects to be created and ready
        uses: jakejarvis/wait-action@master
        with:
          time: '360s'
      - name: Check status on Minikube
        run : | 
          kubectl get pods -n tackle
          kubectl get pods -n microcks
          kubectl logs -l app.kubernetes.io/name=tackle-pathfinder -n tackle
          kubectl logs -l app.kubernetes.io/name=keycloak -n tackle
      - name: API simple tests
        run: .github/scripts/check_api.sh
        shell: bash
      - name: Microcks API load
        run: |
          curl -X POST "https://microcks.$(minikube ip).nip.io/api/artifact/upload" -H "accept: text/plain" -H "Content-Type: multipart/form-data" \
            -F "file=@src/main/resources/META-INF/openapi.json;type=application/json" -L -k
      - name: Microcks execution
        uses: microcks/test-github-action@v1
        with:
          apiNameAndVersion: 'tackle-pathfinder-0.0.2:0.0.2'
          testEndpoint: 'http://$(minikube ip)/pathfinder'
          runner: OPEN_API_SCHEMA
          microcksURL: microcks.$(minikube ip).nip.io
          keycloakClientId:  account
          keycloakClientSecret:  0136c3ef-0dfd-4b13-a6d0-2c8b6358edec
          waitFor: '10sec'
          operationsHeaders: |
            {
              "globals": [
                {
                  "name": "Authorization",
                  "values": "Bearer ${{env.keycloak_token}}"
                }
              ]
            }